#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iFix
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ifixdb")]
	public partial class ifix_DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ifix_DBDataContext() : 
				base(global::iFix.Properties.Settings.Default.ifixdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ifix_DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ifix_DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ifix_DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ifix_DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerServicios")]
		public ISingleResult<obtenerServiciosResult> obtenerServicios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<obtenerServiciosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerVehiculos")]
		public ISingleResult<obtenerVehiculosResult> obtenerVehiculos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<obtenerVehiculosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarClientes")]
		public ISingleResult<mostrarClientesResult> mostrarClientes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrarClientesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarCliente")]
		public int agregarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string numero_de_telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, usuario, contrasena, numero_de_telefono, email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerNombreCliente")]
		public ISingleResult<obtenerNombreClienteResult> obtenerNombreCliente()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<obtenerNombreClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingresarServicio")]
		public int ingresarServicio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(75)")] string nombreServicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> costo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreServicio, costo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.borrarServicio")]
		public int borrarServicio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreServicio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreServicio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.escogerServicio")]
		public ISingleResult<escogerServicioResult> escogerServicio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreServicio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreServicio);
			return ((ISingleResult<escogerServicioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.actualizarServicio")]
		public int actualizarServicio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreServicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nuevoServicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> nuevoCosto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreServicio, nuevoServicio, nuevoCosto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerVehiculos_Cliente")]
		public ISingleResult<obtenerVehiculos_ClienteResult> obtenerVehiculos_Cliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user);
			return ((ISingleResult<obtenerVehiculos_ClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerTipo")]
		public ISingleResult<obtenerTipoResult> obtenerTipo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<obtenerTipoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingresarVehiculo")]
		public int ingresarVehiculo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string num_serie, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string marca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string modelo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> anio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string color, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> alarma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> cristales_electricos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> gps, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> airbag, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string observaciones, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), num_serie, marca, modelo, anio, color, alarma, cristales_electricos, gps, airbag, observaciones, usuario, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerVehiculosEstado")]
		public ISingleResult<obtenerVehiculosEstadoResult> obtenerVehiculosEstado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_edo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_edo);
			return ((ISingleResult<obtenerVehiculosEstadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.borrarCliente")]
		public int borrarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getServicioId")]
		public ISingleResult<getServicioIdResult> getServicioId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreServ)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreServ);
			return ((ISingleResult<getServicioIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getVehiculoId")]
		public ISingleResult<getVehiculoIdResult> getVehiculoId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(17)")] string numSerie)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numSerie);
			return ((ISingleResult<getVehiculoIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerServicioId", IsComposable=true)]
		public System.Nullable<int> obtenerServicioId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreServ)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreServ).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerVehiculoId", IsComposable=true)]
		public System.Nullable<int> obtenerVehiculoId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(17)")] string numSerie)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numSerie).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.setLastIdVehiculoServicio")]
		public int setLastIdVehiculoServicio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVehiculo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idServicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEstadoVehiculo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVehiculo, idServicio, idEstadoVehiculo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerCosto", IsComposable=true)]
		public System.Nullable<double> obtenerCosto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreSer)
		{
			return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreSer).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarVenta")]
		public int agregarVenta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> total, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numServicios)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), total, numServicios);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerServicios_vehiculo")]
		public ISingleResult<obtenerServicios_vehiculoResult> obtenerServicios_vehiculo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_id_vehiculo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_id_vehiculo);
			return ((ISingleResult<obtenerServicios_vehiculoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingresarFechaSalida")]
		public int ingresarFechaSalida([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVehiculo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVehiculo, fechaS);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingresarFechaTerminacion")]
		public int ingresarFechaTerminacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVehiculo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idServicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVehiculo, idServicio, fechaT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerServiciosVehiculoTerminacion")]
		public ISingleResult<obtenerServiciosVehiculoTerminacionResult> obtenerServiciosVehiculoTerminacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_id_vehiculo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_id_vehiculo);
			return ((ISingleResult<obtenerServiciosVehiculoTerminacionResult>)(result.ReturnValue));
		}
	}
	
	public partial class obtenerServiciosResult
	{
		
		private string _nombre;
		
		private double _costo;
		
		public obtenerServiciosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="Float NOT NULL")]
		public double costo
		{
			get
			{
				return this._costo;
			}
			set
			{
				if ((this._costo != value))
				{
					this._costo = value;
				}
			}
		}
	}
	
	public partial class obtenerVehiculosResult
	{
		
		private string _num_serie;
		
		private string _marca;
		
		private string _modelo;
		
		private int _anio;
		
		private string _color;
		
		private System.Nullable<char> _alarma;
		
		private System.Nullable<char> _cristales_electricos;
		
		private System.Nullable<char> _gps;
		
		private System.Nullable<char> _airbag;
		
		private string _observaciones;
		
		public obtenerVehiculosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_serie", DbType="Char(17) NOT NULL", CanBeNull=false)]
		public string num_serie
		{
			get
			{
				return this._num_serie;
			}
			set
			{
				if ((this._num_serie != value))
				{
					this._num_serie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string marca
		{
			get
			{
				return this._marca;
			}
			set
			{
				if ((this._marca != value))
				{
					this._marca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string modelo
		{
			get
			{
				return this._modelo;
			}
			set
			{
				if ((this._modelo != value))
				{
					this._modelo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio", DbType="Int NOT NULL")]
		public int anio
		{
			get
			{
				return this._anio;
			}
			set
			{
				if ((this._anio != value))
				{
					this._anio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(50)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this._color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alarma", DbType="Char(1)")]
		public System.Nullable<char> alarma
		{
			get
			{
				return this._alarma;
			}
			set
			{
				if ((this._alarma != value))
				{
					this._alarma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cristales_electricos", DbType="Char(1)")]
		public System.Nullable<char> cristales_electricos
		{
			get
			{
				return this._cristales_electricos;
			}
			set
			{
				if ((this._cristales_electricos != value))
				{
					this._cristales_electricos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gps", DbType="Char(1)")]
		public System.Nullable<char> gps
		{
			get
			{
				return this._gps;
			}
			set
			{
				if ((this._gps != value))
				{
					this._gps = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airbag", DbType="Char(1)")]
		public System.Nullable<char> airbag
		{
			get
			{
				return this._airbag;
			}
			set
			{
				if ((this._airbag != value))
				{
					this._airbag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="NVarChar(250)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this._observaciones = value;
				}
			}
		}
	}
	
	public partial class mostrarClientesResult
	{
		
		private int _id_cliente;
		
		private string _nombre;
		
		private string _usuario;
		
		private string _contrasena;
		
		private string _numero_de_telefono;
		
		private string _email;
		
		public mostrarClientesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int NOT NULL")]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this._id_cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this._contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_de_telefono", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string numero_de_telefono
		{
			get
			{
				return this._numero_de_telefono;
			}
			set
			{
				if ((this._numero_de_telefono != value))
				{
					this._numero_de_telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
	}
	
	public partial class obtenerNombreClienteResult
	{
		
		private string _nombre;
		
		private string _usuario;
		
		public obtenerNombreClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
	}
	
	public partial class escogerServicioResult
	{
		
		private int _id_servicio;
		
		private string _nombre;
		
		private double _costo;
		
		public escogerServicioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_servicio", DbType="Int NOT NULL")]
		public int id_servicio
		{
			get
			{
				return this._id_servicio;
			}
			set
			{
				if ((this._id_servicio != value))
				{
					this._id_servicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="Float NOT NULL")]
		public double costo
		{
			get
			{
				return this._costo;
			}
			set
			{
				if ((this._costo != value))
				{
					this._costo = value;
				}
			}
		}
	}
	
	public partial class obtenerVehiculos_ClienteResult
	{
		
		private int _id_vehiculo;
		
		private string _foto;
		
		private string _num_serie;
		
		private string _marca;
		
		private string _modelo;
		
		private int _anio;
		
		private string _color;
		
		private System.Nullable<char> _alarma;
		
		private System.Nullable<char> _cristales_electricos;
		
		private System.Nullable<char> _gps;
		
		private System.Nullable<char> _airbag;
		
		private string _observaciones;
		
		private System.Nullable<int> _cliente_id_cliente;
		
		private System.Nullable<int> _c_tipo_de_vehiculo_id_tipo;
		
		public obtenerVehiculos_ClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vehiculo", DbType="Int NOT NULL")]
		public int id_vehiculo
		{
			get
			{
				return this._id_vehiculo;
			}
			set
			{
				if ((this._id_vehiculo != value))
				{
					this._id_vehiculo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="VarChar(30)")]
		public string foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this._foto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_serie", DbType="Char(17) NOT NULL", CanBeNull=false)]
		public string num_serie
		{
			get
			{
				return this._num_serie;
			}
			set
			{
				if ((this._num_serie != value))
				{
					this._num_serie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string marca
		{
			get
			{
				return this._marca;
			}
			set
			{
				if ((this._marca != value))
				{
					this._marca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string modelo
		{
			get
			{
				return this._modelo;
			}
			set
			{
				if ((this._modelo != value))
				{
					this._modelo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio", DbType="Int NOT NULL")]
		public int anio
		{
			get
			{
				return this._anio;
			}
			set
			{
				if ((this._anio != value))
				{
					this._anio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(50)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this._color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alarma", DbType="Char(1)")]
		public System.Nullable<char> alarma
		{
			get
			{
				return this._alarma;
			}
			set
			{
				if ((this._alarma != value))
				{
					this._alarma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cristales_electricos", DbType="Char(1)")]
		public System.Nullable<char> cristales_electricos
		{
			get
			{
				return this._cristales_electricos;
			}
			set
			{
				if ((this._cristales_electricos != value))
				{
					this._cristales_electricos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gps", DbType="Char(1)")]
		public System.Nullable<char> gps
		{
			get
			{
				return this._gps;
			}
			set
			{
				if ((this._gps != value))
				{
					this._gps = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airbag", DbType="Char(1)")]
		public System.Nullable<char> airbag
		{
			get
			{
				return this._airbag;
			}
			set
			{
				if ((this._airbag != value))
				{
					this._airbag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="NVarChar(250)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this._observaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliente_id_cliente", DbType="Int")]
		public System.Nullable<int> cliente_id_cliente
		{
			get
			{
				return this._cliente_id_cliente;
			}
			set
			{
				if ((this._cliente_id_cliente != value))
				{
					this._cliente_id_cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_tipo_de_vehiculo_id_tipo", DbType="Int")]
		public System.Nullable<int> c_tipo_de_vehiculo_id_tipo
		{
			get
			{
				return this._c_tipo_de_vehiculo_id_tipo;
			}
			set
			{
				if ((this._c_tipo_de_vehiculo_id_tipo != value))
				{
					this._c_tipo_de_vehiculo_id_tipo = value;
				}
			}
		}
	}
	
	public partial class obtenerTipoResult
	{
		
		private int _id_tipo;
		
		private string _tipo;
		
		private string _descripcion;
		
		public obtenerTipoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo", DbType="Int NOT NULL")]
		public int id_tipo
		{
			get
			{
				return this._id_tipo;
			}
			set
			{
				if ((this._id_tipo != value))
				{
					this._id_tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this._tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	public partial class obtenerVehiculosEstadoResult
	{
		
		private string _Cliente;
		
		private string _numero_de_telefono;
		
		private string _modelo;
		
		private string _marca;
		
		private string _color;
		
		private string _num_serie;
		
		private int _anio;
		
		private string _estado;
		
		private System.DateTime _fecha_entrada;
		
		private System.Nullable<System.DateTime> _fecha_salida;
		
		private System.Nullable<System.DateTime> _fecha_terminacion;
		
		public obtenerVehiculosEstadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_de_telefono", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string numero_de_telefono
		{
			get
			{
				return this._numero_de_telefono;
			}
			set
			{
				if ((this._numero_de_telefono != value))
				{
					this._numero_de_telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string modelo
		{
			get
			{
				return this._modelo;
			}
			set
			{
				if ((this._modelo != value))
				{
					this._modelo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string marca
		{
			get
			{
				return this._marca;
			}
			set
			{
				if ((this._marca != value))
				{
					this._marca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(50)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this._color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_serie", DbType="Char(17) NOT NULL", CanBeNull=false)]
		public string num_serie
		{
			get
			{
				return this._num_serie;
			}
			set
			{
				if ((this._num_serie != value))
				{
					this._num_serie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio", DbType="Int NOT NULL")]
		public int anio
		{
			get
			{
				return this._anio;
			}
			set
			{
				if ((this._anio != value))
				{
					this._anio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_entrada", DbType="Date NOT NULL")]
		public System.DateTime fecha_entrada
		{
			get
			{
				return this._fecha_entrada;
			}
			set
			{
				if ((this._fecha_entrada != value))
				{
					this._fecha_entrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_salida", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_salida
		{
			get
			{
				return this._fecha_salida;
			}
			set
			{
				if ((this._fecha_salida != value))
				{
					this._fecha_salida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_terminacion", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_terminacion
		{
			get
			{
				return this._fecha_terminacion;
			}
			set
			{
				if ((this._fecha_terminacion != value))
				{
					this._fecha_terminacion = value;
				}
			}
		}
	}
	
	public partial class getServicioIdResult
	{
		
		private int _id_servicio;
		
		public getServicioIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_servicio", DbType="Int NOT NULL")]
		public int id_servicio
		{
			get
			{
				return this._id_servicio;
			}
			set
			{
				if ((this._id_servicio != value))
				{
					this._id_servicio = value;
				}
			}
		}
	}
	
	public partial class getVehiculoIdResult
	{
		
		private int _id_vehiculo;
		
		public getVehiculoIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vehiculo", DbType="Int NOT NULL")]
		public int id_vehiculo
		{
			get
			{
				return this._id_vehiculo;
			}
			set
			{
				if ((this._id_vehiculo != value))
				{
					this._id_vehiculo = value;
				}
			}
		}
	}
	
	public partial class obtenerServicios_vehiculoResult
	{
		
		private string _nombre;
		
		private string _estado;
		
		private double _costo;
		
		private System.Nullable<System.DateTime> _fecha_salida;
		
		public obtenerServicios_vehiculoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="Float NOT NULL")]
		public double costo
		{
			get
			{
				return this._costo;
			}
			set
			{
				if ((this._costo != value))
				{
					this._costo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_salida", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_salida
		{
			get
			{
				return this._fecha_salida;
			}
			set
			{
				if ((this._fecha_salida != value))
				{
					this._fecha_salida = value;
				}
			}
		}
	}
	
	public partial class obtenerServiciosVehiculoTerminacionResult
	{
		
		private string _nombre;
		
		private string _estado;
		
		private double _costo;
		
		private System.Nullable<System.DateTime> _fecha_salida;
		
		public obtenerServiciosVehiculoTerminacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="Float NOT NULL")]
		public double costo
		{
			get
			{
				return this._costo;
			}
			set
			{
				if ((this._costo != value))
				{
					this._costo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_salida", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_salida
		{
			get
			{
				return this._fecha_salida;
			}
			set
			{
				if ((this._fecha_salida != value))
				{
					this._fecha_salida = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
